config/routes.rb
Rails.application.routes.draw do
  # Api documentation
  apipie

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :quotes

  # /api routes
  namespace :api, defaults: { format: :json } do
    get "public" => "test#public", as: :public
    get "protected" => "test#protected", as: :protected

    resources "sessions", only: [ :create ]

    resources :users do
      resource :profile, only: [ :show, :update ]
      resource :clock_ins, only: [ :create ]
    end
    resources :quotes, only: [ :index, :show ]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_one_attached :poster
  has_one_attached :video

  validates :author, presence: true
  validates :content, presence: true, length: { minimum: 10 }
  validate :poster, :validate_poster

  # TODO: custom today
  def self.today
    last
    # where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
  end

  # TODO: optimize
  def poster_url
    attachment_url(poster)
  end

  def video_url
    attachment_url(video)
  end

  private

  def validate_poster
    return unless poster.attached?

    if !poster.content_type.in?(%w[image/png image/jpg image/jpeg])
      errors.add(:poster, "must be a JPEG or PNG.")
    elsif poster.blob.byte_size > 1.megabyte
      errors.add(:poster, "is too large. Maximum size is 1 MB.")
    end
  end

  def attachment_url(attachment)
    Rails.application.routes.url_helpers.rails_blob_url(attachment) if attachment.attached?
  end
end

app/controllers/api/quotes_controller.rb
module Api
  class QuotesController < Api::BaseController
    allow_unauthenticated_access only: :show

    api :GET, "/quotes/today", "Get today's quote"
    description "Get today's quote"
    returns code: 200, desc: "A successful response" do
    end
    def show
      @quote = Quote.today
    end
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all
  end

  def new
    @quote = Quote.new
  end

  def edit
    @quote = Quote.find(params[:id])
  end

  def update
    quote = Quote.find(params[:id])
    quote.update(quote_params)
    redirect_to quotes_path
  end

  def create
    Quote.create(quote_params)
    redirect_to root_path
  end

  def destroy
    Quote.find(params[:id]).destroy
    redirect_to quotes_path
  end

  private

  def quote_params
    params.require(:quote).permit(:content, :author, :poster)
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with model: quote, class: "flex flex-col gap-4" do |form| %>
  <div class="flex flex-col">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>
  <div class="flex flex-col">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="flex flex-col">
    <%= form.label :poster %>
    <%= image_tag quote.poster, class: "h-40 border" if quote.poster.attached? %>
    <%= form.file_field :poster, accept: "image/*" %>
  </div>
  <div class="flex justify-end">
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<div class="h-40 flex border rounded overflow-hidden">
  <%= image_tag quote.poster, class: "!m-0 !w-40 !h-40 object-scale-down border-r" %>
  <div class="flex-1 p-4 flex flex-col justify-between">
    <p class="!m-0 text-xl"><%= quote.content %></p>
    <p class="!m-0 flex items-center justify-end gap-2 text-sm">
      <span>--</span>
      <%= quote.author %>
    </p>
  </div>
</div>

<div class="flex items-baseline justify-between">
  <div>
    <span class="text-xs text-gray-500"><%= quote.created_at %></span>
  </div>
  <div>
    <%= link_to "Edit", edit_quote_path(quote) %>
    <%= link_to "Destroy", quote, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  </div>
</div>

app/views/quotes/edit.html.erb
<%= render "form", quote: @quote %>

app/views/quotes/index.html.erb
<div class="flex flex-col gap-4">
  <%= render @quotes %>
</div>

app/views/quotes/new.html.erb
<%= render "form", quote: @quote %>